name: Service Catalog Meta Data Check
run-name: Catalog check ${{ github.event.client_payload.check }} on ${{ github.event.client_payload.service }}
on:
  repository_dispatch:
    types: ["meta-data-urls"]

jobs:
  meta:
    env:
      SERVICE_CATALOG_TOKEN: ${{ secrets.SERVICE_CATALOG_TOKEN }}
    runs-on: ubuntu-latest
    steps:
    - uses: clearwind-ca/get-payload@main
    - uses: actions/setup-python@v4
    - uses: actions/checkout@v3
    - run: |
        python check-metadata.py
    - uses: clearwind-ca/send-result@main
    - if: failure()
      uses: clearwind-ca/send-result@inputs
      with:
        result: "error"
